export const telecode = [
  { name: 'Afghanistan', tel: 93, iso: 'AF', iso3: 'AFG' },
  { name: 'Albania', tel: 355, iso: 'AL', iso3: 'ALB' },
  { name: 'Algeria', tel: 213, iso: 'DZ', iso3: 'DZA' },
  { name: 'American Samoa', tel: 1684, iso: 'AS', iso3: 'ASM' },
  { name: 'Andorra', tel: 376, iso: 'AD', iso3: 'AND' },
  { name: 'Angola', tel: 244, iso: 'AO', iso3: 'AGO' },
  { name: 'Anguilla', tel: 1264, iso: 'AI', iso3: 'AIA' },
  { name: 'Antarctica', tel: 672, iso: 'AQ', iso3: 'ATA' },
  { name: 'Antigua and Barbuda', tel: 1268, iso: 'AG', iso3: 'ATG' },
  { name: 'Argentina', tel: 54, iso: 'AR', iso3: 'ARG' },
  { name: 'Armenia', tel: 374, iso: 'AM', iso3: 'ARM' },
  { name: 'Aruba', tel: 297, iso: 'AW', iso3: 'ABW' },
  { name: 'Australia', tel: 61, iso: 'AU', iso3: 'AUS' },
  { name: 'Austria', tel: 43, iso: 'AT', iso3: 'AUT' },
  { name: 'Azerbaijan', tel: 994, iso: 'AZ', iso3: 'AZE' },
  { name: 'Bahamas', tel: 1242, iso: 'BS', iso3: 'BHS' },
  { name: 'Bahrain', tel: 973, iso: 'BH', iso3: 'BHR' },
  { name: 'Bangladesh', tel: 880, iso: 'BD', iso3: 'BGD' },
  { name: 'Barbados', tel: 1246, iso: 'BB', iso3: 'BRB' },
  { name: 'Belarus', tel: 375, iso: 'BY', iso3: 'BLR' },
  { name: 'Belgium', tel: 32, iso: 'BE', iso3: 'BEL' },
  { name: 'Belize', tel: 501, iso: 'BZ', iso3: 'BLZ' },
  { name: 'Benin', tel: 229, iso: 'BJ', iso3: 'BEN' },
  { name: 'Bermuda', tel: 1441, iso: 'BM', iso3: 'BMU' },
  { name: 'Bhutan', tel: 975, iso: 'BT', iso3: 'BTN' },
  { name: 'Bolivia', tel: 591, iso: 'BO', iso3: 'BOL' },
  { name: 'Bosnia and Herzegovina', tel: 387, iso: 'BA', iso3: 'BIH' },
  { name: 'Botswana', tel: 267, iso: 'BW', iso3: 'BWA' },
  { name: 'Brazil', tel: 55, iso: 'BR', iso3: 'BRA' },
  { name: 'British Indian Ocean Territory', tel: 246, iso: 'IO', iso3: 'IOT' },
  { name: 'British Virgin Islands', tel: 1284, iso: 'VG', iso3: 'VGB' },
  { name: 'Brunei', tel: 673, iso: 'BN', iso3: 'BRN' },
  { name: 'Bulgaria', tel: 359, iso: 'BG', iso3: 'BGR' },
  { name: 'Burkina Faso', tel: 226, iso: 'BF', iso3: 'BFA' },
  { name: 'Burundi', tel: 257, iso: 'BI', iso3: 'BDI' },
  { name: 'Cambodia', tel: 855, iso: 'KH', iso3: 'KHM' },
  { name: 'Cameroon', tel: 237, iso: 'CM', iso3: 'CMR' },
  { name: 'Canada', tel: 1, iso: 'CA', iso3: 'CAN' },
  { name: 'Cape Verde', tel: 238, iso: '', iso3: 'CPV' },
  { name: 'Cayman Islands', tel: 1345, iso: 'KY', iso3: 'CYM' },
  { name: 'Central African Republic', tel: 236, iso: 'CF', iso3: 'CAF' },
  { name: 'Chad', tel: 235, iso: 'TD', iso3: 'TCD' },
  { name: 'Chile', tel: 56, iso: 'CL', iso3: 'CHL' },
  { name: 'China', tel: 86, iso: 'CN', iso3: 'CHN' },
  { name: 'Christmas Island', tel: 61, iso: 'CX', iso3: 'CXR' },
  { name: 'Cocos Islands', tel: 61, iso: 'CC', iso3: 'CCK' },
  { name: 'Colombia', tel: 57, iso: 'CO', iso3: 'COL' },
  { name: 'Comoros', tel: 269, iso: 'KM', iso3: 'COM' },
  { name: 'Democratic Republic of the Congo', tel: 243, iso: '', iso3: 'COD' },
  { name: 'Denmark', tel: 45, iso: 'DK', iso3: 'DNK' },
  { name: 'Djibouti', tel: 253, iso: 'DJ', iso3: 'DJI' },
  { name: 'Dominica', tel: 1767, iso: 'DM', iso3: 'DMA' },
  { name: 'Dominican Republic', tel: 1849, iso: 'DO', iso3: 'DOM' },
  { name: 'East Timor', tel: 670, iso: '', iso3: 'TLS' },
  { name: 'Ecuador', tel: 593, iso: 'EC', iso3: 'ECU' },
  { name: 'Egypt', tel: 20, iso: 'EG', iso3: 'EGY' },
  { name: 'El Salvador', tel: 503, iso: 'SV', iso3: 'SLV' },
  { name: 'Equatorial Guinea', tel: 240, iso: 'GQ', iso3: 'GNQ' },
  { name: 'Eritrea', tel: 291, iso: 'ER', iso3: 'ERI' },
  { name: 'Estonia', tel: 372, iso: 'EE', iso3: 'EST' },
  { name: 'Ethiopia', tel: 251, iso: 'ET', iso3: 'ETH' },
  { name: 'Falkland Islands', tel: 500, iso: 'FK', iso3: 'FLK' },
  { name: 'Faroe Islands', tel: 298, iso: 'FO', iso3: 'FRO' },
  { name: 'Fiji', tel: 679, iso: 'FJ', iso3: 'FJI' },
  { name: 'Finland', tel: 358, iso: 'FI', iso3: 'FIN' },
  { name: 'France', tel: 33, iso: 'FR', iso3: 'FRA' },
  { name: 'French Polynesia', tel: 689, iso: 'PF', iso3: 'PYF' },
  { name: 'Gabon', tel: 241, iso: 'GA', iso3: 'GAB' },
  { name: 'Gambia', tel: 220, iso: 'GM', iso3: 'GMB' },
  { name: 'Georgia', tel: 995, iso: 'GE', iso3: 'GEO' },
  { name: 'Germany', tel: 49, iso: 'DE', iso3: 'DEU' },
  { name: 'Ghana', tel: 233, iso: 'GH', iso3: 'GHA' },
  { name: 'Gibraltar', tel: 350, iso: 'GI', iso3: 'GIB' },
  { name: 'Greece', tel: 30, iso: 'GR', iso3: 'GRC' },
  { name: 'Greenland', tel: 299, iso: 'GL', iso3: 'GRL' },
  { name: 'Grenada', tel: 1473, iso: 'GD', iso3: 'GRD' },
  { name: 'Guam', tel: 1671, iso: 'GU', iso3: 'GUM' },
  { name: 'Guatemala', tel: 502, iso: 'GT', iso3: 'GTM' },
  { name: 'Guernsey', tel: 441481, iso: 'GG', iso3: 'GGY' },
  { name: 'Guinea', tel: 224, iso: 'GN', iso3: 'GIN' },
  { name: 'Guinea-Bissau', tel: 245, iso: 'GW', iso3: 'GNB' },
  { name: 'Guyana', tel: 592, iso: 'GY', iso3: 'GUY' },
  { name: 'Haiti', tel: 509, iso: 'HT', iso3: 'HTI' },
  { name: 'Honduras', tel: 504, iso: 'HN', iso3: 'HND' },
  { name: 'Hong Kong', tel: 852, iso: 'HK', iso3: 'HKG' },
  { name: 'Hungary', tel: 36, iso: 'HU', iso3: 'HUN' },
  { name: 'Iceland', tel: 354, iso: 'IS', iso3: 'ISL' },
  { name: 'India', tel: 91, iso: 'IN', iso3: 'IND' },
  { name: 'Indonesia', tel: 62, iso: 'ID', iso3: 'IDN' },
  { name: 'Iran', tel: 98, iso: 'IR', iso3: 'IRN' },
  { name: 'Iraq', tel: 964, iso: 'IQ', iso3: 'IRQ' },
  { name: 'Ireland', tel: 353, iso: 'IE', iso3: 'IRL' },
  { name: 'Isle of Man', tel: 441624, iso: 'IM', iso3: 'IMN' },
  { name: 'Israel', tel: 972, iso: 'IL', iso3: 'ISR' },
  { name: 'Italy', tel: 39, iso: 'IT', iso3: 'ITA' },
  { name: 'Ivory Coast', tel: 225, iso: 'CI', iso3: 'CIV' },
  { name: 'Jamaica', tel: 1876, iso: 'JM', iso3: 'JAM' },
  { name: 'Japan', tel: 81, iso: 'JP', iso3: 'JPN' },
  { name: 'Jersey', tel: 441534, iso: 'JE', iso3: 'JEY' },
  { name: 'Jordan', tel: 962, iso: 'JO', iso3: 'JOR' },
  { name: 'Kazakhstan', tel: 7, iso: 'KZ', iso3: 'KAZ' },
  { name: 'Kenya', tel: 254, iso: 'KE', iso3: 'KEN' },
  { name: 'Kiribati', tel: 686, iso: 'KI', iso3: 'KIR' },
  { name: 'Kosovo', tel: 383, iso: 'XK', iso3: 'XKX' },
  { name: 'Kuwait', tel: 965, iso: 'KW', iso3: 'KWT' },
  { name: 'Kyrgyzstan', tel: 996, iso: 'KG', iso3: 'KGZ' },
  { name: 'Laos', tel: 856, iso: 'LA', iso3: 'LAO' },
  { name: 'Latvia', tel: 371, iso: 'LV', iso3: 'LVA' },
  { name: 'Lebanon', tel: 961, iso: 'LB', iso3: 'LBN' },
  { name: 'Lesotho', tel: 266, iso: 'LS', iso3: 'LSO' },
  { name: 'Liberia', tel: 231, iso: 'LR', iso3: 'LBR' },
  { name: 'Libya', tel: 218, iso: 'LY', iso3: 'LBY' },
  { name: 'Liechtenstein', tel: 423, iso: 'LI', iso3: 'LIE' },
  { name: 'Lithuania', tel: 370, iso: '', iso3: 'LTU' },
  { name: 'Luxembourg', tel: 352, iso: 'LU', iso3: 'LUX' },
  { name: 'Macau', tel: 853, iso: 'MO', iso3: 'MAC' },
  { name: 'Macedonia', tel: 389, iso: 'MK', iso3: 'MKD' },
  { name: 'Madagascar', tel: 261, iso: 'MG', iso3: 'MDG' },
  { name: 'Malawi', tel: 265, iso: 'MW', iso3: 'MWI' },
  { name: 'Malaysia', tel: 60, iso: 'MY', iso3: 'MYS' },
  { name: 'Maldives', tel: 960, iso: 'MV', iso3: 'MDV' },
  { name: 'Mali', tel: 223, iso: 'ML', iso3: 'MLI' },
  { name: 'Malta', tel: 356, iso: 'MT', iso3: 'MLT' },
  { name: 'Marshall Islands', tel: 692, iso: 'MH', iso3: 'MHL' },
  { name: 'Mauritania', tel: 222, iso: 'MR', iso3: 'MRT' },
  { name: 'Mauritius', tel: 230, iso: 'MU', iso3: 'MUS' },
  { name: 'Mayotte', tel: 262, iso: 'YT', iso3: 'MYT' },
  { name: 'Mexico', tel: 52, iso: 'MX', iso3: 'MEX' },
  { name: 'Micronesia', tel: 691, iso: '', iso3: 'FSM' },
  { name: 'Moldova', tel: 373, iso: '', iso3: 'MDA' },
  { name: 'Monaco', tel: 377, iso: 'MC', iso3: 'MCO' },
  { name: 'Mongolia', tel: 976, iso: 'MN', iso3: 'MNG' },
  { name: 'Montenegro', tel: 382, iso: 'ME', iso3: 'MNE' },
  { name: 'Montserrat', tel: 1664, iso: 'MS', iso3: 'MSR' },
  { name: 'Morocco', tel: 212, iso: 'MA', iso3: 'MAR' },
  { name: 'Mozambique', tel: 258, iso: 'MZ', iso3: 'MOZ' },
  { name: 'Namibia', tel: 264, iso: 'NA', iso3: 'NAM' },
  { name: 'Nauru', tel: 674, iso: 'NR', iso3: 'NRU' },
  { name: 'Nepal', tel: 977, iso: 'NP', iso3: 'NPL' },
  { name: 'Netherlands', tel: 31, iso: 'NL', iso3: 'NLD' },
  { name: 'Netherlands Antilles', tel: 599, iso: '', iso3: 'ANT' },
  { name: 'New Caledonia', tel: 687, iso: 'NC', iso3: 'NCL' },
  { name: 'New Zealand', tel: 64, iso: 'NZ', iso3: 'NZL' },
  { name: 'Nicaragua', tel: 505, iso: 'NI', iso3: 'NIC' },
  { name: 'Niger', tel: 227, iso: 'NE', iso3: 'NER' },
  { name: 'Nigeria', tel: 234, iso: 'NG', iso3: 'NGA' },
  { name: 'Niue', tel: 683, iso: 'NU', iso3: 'NIU' },
  { name: 'North Korea', tel: 850, iso: 'KP', iso3: 'MNP' },
  { name: 'Northern Mariana Islands', tel: 1670, iso: 'MP', iso3: 'PRK' },
  { name: 'Norway', tel: 47, iso: 'NO', iso3: 'NOR' },
  { name: 'Oman', tel: 968, iso: 'OM', iso3: 'OMN' },
  { name: 'Pakistan', tel: 92, iso: 'PK', iso3: 'PAK' },
  { name: 'Palau', tel: 680, iso: 'PW', iso3: 'PLW' },
  { name: 'Palestine', tel: 970, iso: 'PS', iso3: 'PSE' },
  { name: 'Panama', tel: 507, iso: 'PA', iso3: 'PAN' },
  { name: 'Papua New Guinea', tel: 675, iso: 'PG', iso3: 'PNG' },
  { name: 'Paraguay', tel: 595, iso: 'PY', iso3: 'PRY' },
  { name: 'Peru', tel: 51, iso: 'PE', iso3: 'PER' },
  { name: 'Philippines', tel: 63, iso: 'PH', iso3: 'PHL' },
  { name: 'Pitcairn', tel: 64, iso: 'PN', iso3: 'PCN' },
  { name: 'Poland', tel: 48, iso: 'PL', iso3: 'POL' },
  { name: 'Portugal', tel: 351, iso: 'PT', iso3: 'PRT' },
  { name: 'Puerto Rico', tel: 1939, iso: 'PR', iso3: 'PRI' },
  { name: 'Qatar', tel: 974, iso: 'QA', iso3: 'QAT' },
  { name: 'Reunion', tel: 262, iso: 'RO', iso3: 'REU' },
  { name: 'Romania', tel: 40, iso: '', iso3: 'ROU' },
  { name: 'Russia', tel: 7, iso: 'RU', iso3: 'RUS' },
  { name: 'Rwanda', tel: 250, iso: 'RW', iso3: 'RWA' },
  { name: 'Saint Barthelemy', tel: 590, iso: '', iso3: 'BLM' },
  { name: 'Samoa', tel: 685, iso: 'WS', iso3: 'WSM' },
  { name: 'San Marino', tel: 378, iso: 'SM', iso3: 'SMR' },
  { name: 'Sao Tome and Principe', tel: 239, iso: '', iso3: 'STP' },
  { name: 'Saudi Arabia', tel: 966, iso: 'SA', iso3: 'SAU' },
  { name: 'Senegal', tel: 221, iso: 'SN', iso3: 'SEN' },
  { name: 'Serbia', tel: 381, iso: 'RS', iso3: 'SRB' },
  { name: 'Seychelles', tel: 248, iso: 'SC', iso3: 'SYC' },
  { name: 'Sierra Leone', tel: 232, iso: 'SL', iso3: 'SLE' },
  { name: 'Singapore', tel: 65, iso: 'SG', iso3: 'SGP' },
  { name: 'Sint Maarten', tel: 1721, iso: 'SX', iso3: 'SXM' },
  { name: 'Slovakia', tel: 421, iso: 'SK', iso3: 'SVK' },
  { name: 'Slovenia', tel: 386, iso: 'SI', iso3: 'SVN' },
  { name: 'Solomon Islands', tel: 677, iso: 'SB', iso3: 'SLB' },
  { name: 'Somalia', tel: 252, iso: 'SO', iso3: 'SOM' },
  { name: 'South Africa', tel: 27, iso: 'ZA', iso3: 'ZAF' },
  { name: 'South Korea', tel: 82, iso: '', iso3: 'KOR' },
  { name: 'South Sudan', tel: 211, iso: 'SS', iso3: 'SSD' },
  { name: 'Spain', tel: 34, iso: 'ES', iso3: 'ESP' },
  { name: 'Sri Lanka', tel: 94, iso: 'LK', iso3: 'LKA' },
  { name: 'Sudan', tel: 249, iso: 'SD', iso3: 'SDN' },
  { name: 'Suriname', tel: 597, iso: 'SR', iso3: 'SUR' },
  { name: 'Svalbard and Jan Mayen', tel: 47, iso: 'SJ', iso3: 'SJM' },
  { name: 'Swaziland', tel: 268, iso: 'SZ', iso3: 'SWZ' },
  { name: 'Sweden', tel: 46, iso: 'SE', iso3: 'SWE' },
  { name: 'Switzerland', tel: 41, iso: 'CH', iso3: 'CHE' },
  { name: 'Syria', tel: 963, iso: 'SY', iso3: 'SYR' },
  { name: 'Taiwan', tel: 886, iso: 'TW', iso3: 'TWN' },
  { name: 'Tajikistan', tel: 992, iso: 'TJ', iso3: 'TJK' },
  { name: 'Tanzania', tel: 255, iso: 'TZ', iso3: 'TZA' },
  { name: 'Thailand', tel: 66, iso: 'TH', iso3: 'THA' },
  { name: 'Togo', tel: 228, iso: 'TG', iso3: 'TGO' },
  { name: 'Tokelau', tel: 690, iso: 'TK', iso3: 'TKL' },
  { name: 'Tonga', tel: 676, iso: 'TO', iso3: 'TON' },
  { name: 'Trinidad and Tobago', tel: 1868, iso: 'TT', iso3: 'TTO' },
  { name: 'Tunisia', tel: 216, iso: 'TN', iso3: 'TUN' },
  { name: 'Turkey', tel: 90, iso: 'TR', iso3: 'TUR' },
  { name: 'Turkmenistan', tel: 993, iso: 'TM', iso3: 'TKM' },
  { name: 'Turks and Caicos Islands', tel: 1649, iso: 'TC', iso3: 'TCA' },
  { name: 'Tuvalu', tel: 688, iso: 'TV', iso3: 'TUV' },
  { name: 'U.S. Virgin Islands', tel: 1340, iso: 'VI', iso3: 'VIR' },
  { name: 'Uganda', tel: 256, iso: 'UG', iso3: 'UGA' },
  { name: 'Ukraine', tel: 380, iso: 'UA', iso3: 'UKR' },
  { name: 'United Arab Emirates', tel: 971, iso: 'AE', iso3: 'ARE' },
  { name: 'United Kingdom', tel: 44, iso: 'GB', iso3: 'GBR' },
  { name: 'United States', tel: 1, iso: 'US', iso3: 'USA' },
  { name: 'Uruguay', tel: 598, iso: 'UY', iso3: 'URY' },
  { name: 'Uzbekistan', tel: 998, iso: 'UZ', iso3: 'UZB' },
  { name: 'Vanuatu', tel: 678, iso: 'VU', iso3: 'VUT' },
  { name: 'Vatican', tel: 379, iso: 'VA', iso3: 'VAT' },
  { name: 'Venezuela', tel: 58, iso: 'VE', iso3: 'VEN' },
  { name: 'Vietnam', tel: 84, iso: 'VN', iso3: 'VNM' },
  { name: 'Wallis and Futuna', tel: 681, iso: 'WF', iso3: 'WLF' },
  { name: 'Western Sahara', tel: 212, iso: 'EH', iso3: 'ESH' },
  { name: 'Yemen', tel: 967, iso: 'YE', iso3: 'YEM' },
  { name: 'Zambia', tel: 260, iso: 'ZM', iso3: 'ZMB' },
  { name: 'Zimbabwe', tel: 263, iso: 'ZW', iso3: 'ZWE' }
];
