import { images } from './images';

export const icons = {
  category: [
    { id: 0, icon: () => images.icon1 },
    { id: 1, icon: () => images.icon2 },
    { id: 2, icon: () => images.icon3 },
    { id: 3, icon: () => images.icon5 },
    { id: 4, icon: () => images.icon6 },
    { id: 5, icon: () => images.icon19 },
    { id: 6, icon: () => images.icon17 },
    { id: 7, icon: () => images.icon7 },
    { id: 8, icon: () => images.icon16 },
    { id: 9, icon: () => images.icon21 },
    { id: 10, icon: () => images.icon20 },
    { id: 11, icon: () => images.icon8 },
    { id: 12, icon: () => images.icon9 },
    { id: 13, icon: () => images.icon10 },
    { id: 14, icon: () => images.icon11 },
    { id: 15, icon: () => images.icon12 },
    { id: 16, icon: () => images.icon13 },
    { id: 17, icon: () => images.icon14 },
    { id: 18, icon: () => images.icon15 },
    { id: 19, icon: () => images.icon18 }
  ],
  brands: [
    { id: 0, icon: () => images.b0 },
    { id: 1, icon: () => images.b1 },
    { id: 2, icon: () => images.b2 },
    { id: 3, icon: () => images.b3 },
    { id: 4, icon: () => images.b4 },
    { id: 5, icon: () => images.b5 },
    { id: 6, icon: () => images.b6 },
    { id: 7, icon: () => images.b7 },
    { id: 8, icon: () => images.b8 },
    { id: 9, icon: () => images.b9 },
    { id: 10, icon: () => images.b10 },
    { id: 11, icon: () => images.b11 },
    { id: 12, icon: () => images.b12 },
    { id: 13, icon: () => images.b13 },
    { id: 14, icon: () => images.b14 },
    { id: 15, icon: () => images.b15 },
    { id: 16, icon: () => images.b16 },
    { id: 17, icon: () => images.b17 },
    { id: 18, icon: () => images.b18 },
    { id: 19, icon: () => images.b19 },
    { id: 20, icon: () => images.b20 },
    { id: 21, icon: () => images.b21 },
    { id: 22, icon: () => images.b22 },
    { id: 23, icon: () => images.b23 },
    { id: 24, icon: () => images.b24 },
    { id: 25, icon: () => images.b25 },
    { id: 26, icon: () => images.b26 },
    { id: 27, icon: () => images.b27 },
    { id: 28, icon: () => images.b28 },
    { id: 29, icon: () => images.b29 },
    { id: 30, icon: () => images.b30 },
    { id: 31, icon: () => images.b31 },
    { id: 32, icon: () => images.b32 },
    { id: 33, icon: () => images.b33 },
    { id: 34, icon: () => images.b34 },
    { id: 35, icon: () => images.b35 },
    { id: 36, icon: () => images.b36 },
    { id: 37, icon: () => images.b37 },
    { id: 38, icon: () => images.b38 },
    { id: 39, icon: () => images.b39 },
    { id: 40, icon: () => images.b40 },
    { id: 41, icon: () => images.b41 },
    { id: 42, icon: () => images.b42 },
    { id: 43, icon: () => images.b43 },
    { id: 44, icon: () => images.b44 },
    { id: 45, icon: () => images.b45 },
    { id: 46, icon: () => images.b46 },
    { id: 47, icon: () => images.b47 },
    { id: 48, icon: () => images.b48 },
    { id: 50, icon: () => images.b50 },
    { id: 51, icon: () => images.b51 },
    { id: 52, icon: () => images.b52 },
    { id: 53, icon: () => images.b53 },
    { id: 54, icon: () => images.b54 },
    { id: 55, icon: () => images.b55 },
    { id: 56, icon: () => images.b56 },
    { id: 57, icon: () => images.b57 },
    { id: 58, icon: () => images.b58 },
    { id: 59, icon: () => images.b59 },
    { id: 60, icon: () => images.b60 },
    { id: 61, icon: () => images.b61 },
    { id: 62, icon: () => images.b62 },
    { id: 63, icon: () => images.b63 },
    { id: 64, icon: () => images.b64 },
    { id: 65, icon: () => images.b65 },
    { id: 66, icon: () => images.b66 },
    { id: 67, icon: () => images.b67 },
    { id: 68, icon: () => images.b68 },
    { id: 69, icon: () => images.b69 },
    { id: 70, icon: () => images.b70 },
    { id: 71, icon: () => images.b71 },
    { id: 72, icon: () => images.b72 },
    { id: 73, icon: () => images.b73 }
  ],
  filterIcons: [
    { id: 'sortType', icon: () => images.sortType },
    { id: 'city', icon: () => images.city },
    { id: 'kindId', icon: () => images.kindId },
    { id: 'realestateId', icon: () => images.realestateId },
    { id: 'serviceId', icon: () => images.serviceId },
    { id: 'brandId', icon: () => images.brandId },
    { id: 'subBrandId', icon: () => images.subBrandId },
    { id: 'eBrandId', icon: () => images.eBrandId },
    { id: 'isnew', icon: () => images.isnew },
    { id: 'issale', icon: () => images.issale },
    { id: 'isfurnishered', icon: () => images.isfurnishered },
    { id: 'rooms', icon: () => images.rooms },
    { id: 'bathrooms', icon: () => images.bathrooms },
    { id: 'year', icon: () => images.year }
  ],
  home: { id: 'home', icon: () => images.home },
  mainmenu: { id: 'menu', icon: () => images.menu },
  namelogo: { id: 'menu', icon: () => images.namelogo },
  search: { id: 'menu', icon: () => images.search },
  itemmenuicon: { id: 'itemmenuicon', icon: () => images.itemmenuicon },
  itemmenuiconup: { id: 'itemmenuiconup', icon: () => images.itemmenuiconup },

  menu: [
    { id: 0, icon: 'ios-person' },
    { id: 1, icon: 'md-add' },
    { id: 2, icon: 'ios-calendar' },
    { id: 3, icon: 'ios-bookmark' },
    { id: 4, icon: 'ios-settings' },
    { id: 5, icon: 'ios-help-circle' },
    { id: 6, icon: 'ios-exit' }
  ],
  flag: [
    { id: 'DZ', icon: () => images.DZ },
    { id: 'AT', icon: () => images.AT },
    { id: 'BH', icon: () => images.BH },
    { id: 'BE', icon: () => images.BE },
    { id: 'CA', icon: () => images.CA },
    { id: 'EG', icon: () => images.EG },
    { id: 'AE', icon: () => images.AE },
    { id: 'FR', icon: () => images.FR },
    { id: 'DE', icon: () => images.DE },
    { id: 'GR', icon: () => images.GR },
    { id: 'ID', icon: () => images.ID },
    { id: 'IR', icon: () => images.IR },
    { id: 'IQ', icon: () => images.IQ },
    { id: 'IT', icon: () => images.IT },
    { id: 'JO', icon: () => images.JO },
    { id: 'KW', icon: () => images.KW },
    { id: 'LB', icon: () => images.LB },
    { id: 'MA', icon: () => images.MA },
    { id: 'QA', icon: () => images.QA },
    { id: 'RU', icon: () => images.RU },
    { id: 'SA', icon: () => images.SA },
    { id: 'ES', icon: () => images.ES },
    { id: 'CH', icon: () => images.CH },
    { id: 'SY', icon: () => images.SY },
    { id: 'TR', icon: () => images.TR },
    { id: 'GB', icon: () => images.GB },
    { id: 'US', icon: () => images.US },
    { id: 'YE', icon: () => images.YE }
  ]
};
